// This file was generated by cmd
package optional

import "encoding/json"

// Float64 represents an float64 that may be optional
type Float64 struct {
	value *float64
}

// NewFloat64 creates an optional.Float64
func NewFloat64(val float64) Float64 {
	return Float64{
		value: &val,
	}
}

// SetValue sets the float64 value
func (opt *Float64) SetValue(val float64) {
	opt.value = &val
}

func (opt Float64) initValue() float64 {
	var val float64
	return val
}

// Value returns the float64 value or init value if not present
func (opt Float64) Value() float64 {
	if opt.value != nil {
		return *opt.value
	} else {
		return opt.initValue()
	}
}

// IsPresent returns whether or not the value is present
func (opt Float64) IsPresent() bool {
	return opt.value != nil
}

// MarshalJSON implements the json.MarshalJSON interface
func (opt Float64) MarshalJSON() ([]byte, error) {
	if opt.value != nil {
		return json.Marshal(opt.value)
	}
	return json.Marshal(nil)
}

// UnmarshalJSON implements the json.UnmarshalJSON interface
func (opt *Float64) UnmarshalJSON(data []byte) error {
	opt.value = nil

	if data == nil {
		return nil
	}

	if string(data) == "null" {
		return nil
	}

	var val float64
	if err := json.Unmarshal(data, &val); err != nil {
		return err
	}

	opt.value = &val
	return nil
}
