// This file was generated by cmd
package optional

import "encoding/json"

// Int8 represents an int8 that may be optional
type Int8 struct {
	value *int8
}

// NewInt8 creates an optional.Int8
func NewInt8(val int8) Int8 {
	return Int8{
		value: &val,
	}
}

// SetValue sets the int8 value
func (opt *Int8) SetValue(val int8) {
	opt.value = &val
}

func (opt Int8) initValue() int8 {
	var val int8
	return val
}

// Value returns the int8 value or init value if not present
func (opt Int8) Value() int8 {
	if opt.value != nil {
		return *opt.value
	} else {
		return opt.initValue()
	}
}

// IsPresent returns whether or not the value is present
func (opt Int8) IsPresent() bool {
	return opt.value != nil
}

// MarshalJSON implements the json.MarshalJSON interface
func (opt Int8) MarshalJSON() ([]byte, error) {
	if opt.value != nil {
		return json.Marshal(opt.value)
	}
	return json.Marshal(nil)
}

// UnmarshalJSON implements the json.UnmarshalJSON interface
func (opt *Int8) UnmarshalJSON(data []byte) error {
	opt.value = nil

	if data == nil {
		return nil
	}

	if string(data) == "null" {
		return nil
	}

	var val int8
	if err := json.Unmarshal(data, &val); err != nil {
		return err
	}

	opt.value = &val
	return nil
}
