// This file was generated by cmd
package optional

import "encoding/json"

// String represents an string that may be optional
type String struct {
	value *string
}

// NewString creates an optional.String
func NewString(val string) String {
	return String{
		value: &val,
	}
}

// SetValue sets the string value
func (opt *String) SetValue(val string) {
	opt.value = &val
}

func (opt String) initValue() string {
	var val string
	return val
}

// Value returns the string value or init value if not present
func (opt String) Value() string {
	if opt.value != nil {
		return *opt.value
	} else {
		return opt.initValue()
	}
}

// IsPresent returns whether or not the value is present
func (opt String) IsPresent() bool {
	return opt.value != nil
}

// MarshalJSON implements the json.MarshalJSON interface
func (opt String) MarshalJSON() ([]byte, error) {
	if opt.value != nil {
		return json.Marshal(opt.value)
	}
	return json.Marshal(nil)
}

// UnmarshalJSON implements the json.UnmarshalJSON interface
func (opt *String) UnmarshalJSON(data []byte) error {
	opt.value = nil

	if data == nil {
		return nil
	}

	if string(data) == "null" {
		return nil
	}

	var val string
	if err := json.Unmarshal(data, &val); err != nil {
		return err
	}

	opt.value = &val
	return nil
}
