// This file was generated by cmd
package optional

import "encoding/json"

// Uint64 represents an uint64 that may be optional
type Uint64 struct {
	value *uint64
}

// NewUint64 creates an optional.Uint64
func NewUint64(val uint64) Uint64 {
	return Uint64{
		value: &val,
	}
}

// SetValue sets the uint64 value
func (opt *Uint64) SetValue(val uint64) {
	opt.value = &val
}

func (opt Uint64) initValue() uint64 {
	var val uint64
	return val
}

// Value returns the uint64 value or init value if not present
func (opt Uint64) Value() uint64 {
	if opt.value != nil {
		return *opt.value
	} else {
		return opt.initValue()
	}
}

// IsPresent returns whether or not the value is present
func (opt Uint64) IsPresent() bool {
	return opt.value != nil
}

// MarshalJSON implements the json.MarshalJSON interface
func (opt Uint64) MarshalJSON() ([]byte, error) {
	if opt.value != nil {
		return json.Marshal(opt.value)
	}
	return json.Marshal(nil)
}

// UnmarshalJSON implements the json.UnmarshalJSON interface
func (opt *Uint64) UnmarshalJSON(data []byte) error {
	opt.value = nil

	if data == nil {
		return nil
	}

	if string(data) == "null" {
		return nil
	}

	var val uint64
	if err := json.Unmarshal(data, &val); err != nil {
		return err
	}

	opt.value = &val
	return nil
}
