// This file was generated by cmd
package optional

import "encoding/json"

// Uint8 represents an uint8 that may be optional
type Uint8 struct {
	value *uint8
}

// NewUint8 creates an optional.Uint8
func NewUint8(val uint8) Uint8 {
	return Uint8{
		value: &val,
	}
}

// SetValue sets the uint8 value
func (opt *Uint8) SetValue(val uint8) {
	opt.value = &val
}

func (opt Uint8) initValue() uint8 {
	var val uint8
	return val
}

// Value returns the uint8 value or init value if not present
func (opt Uint8) Value() uint8 {
	if opt.value != nil {
		return *opt.value
	} else {
		return opt.initValue()
	}
}

// IsPresent returns whether or not the value is present
func (opt Uint8) IsPresent() bool {
	return opt.value != nil
}

// MarshalJSON implements the json.MarshalJSON interface
func (opt Uint8) MarshalJSON() ([]byte, error) {
	if opt.value != nil {
		return json.Marshal(opt.value)
	}
	return json.Marshal(nil)
}

// UnmarshalJSON implements the json.UnmarshalJSON interface
func (opt *Uint8) UnmarshalJSON(data []byte) error {
	opt.value = nil

	if data == nil {
		return nil
	}

	if string(data) == "null" {
		return nil
	}

	var val uint8
	if err := json.Unmarshal(data, &val); err != nil {
		return err
	}

	opt.value = &val
	return nil
}
